### ISSUE TITLE
Jetbrains 제품군에서 다양한 오동작이 발생 (IntelliJ, Webstorm 등)

### ISSUE THREAD

**Issue by youknowone** [gureum/gureum#149]
이 이슈는 다른 이슈를 추적하기 위한 이슈입니다.
- [ ] #45 #128: IntelliJ 계열 입력기에서 기본배열과 다르면서 조합없이 입력되는 문자 입력이 정상적으로 되지 않는 문제
- [ ] #83: 자판 전환으로 시프트 스페이스를 사용할 경우 스페이스가 함께 입력되는 문제
- [ ] #23 #92 #185 #184: 시프트스페이스로 자판 전환 후 첫 스페이스나 리턴 등의 입력이 무시되는 문제
- [ ] #200

내용 추가: 인텔리제이 제품군 관련 오류는 빠른 시일 내에 해결 가능성이 낮습니다.

**Comment by yevgnenll** [comment]
우왕 고생하셨습니다~

**Comment by eugenefox** [comment]
아직 해결되지 않은 이슈인가 보네요.
#45 이슈와 비슷한 것 갈은데, IntelliJ에서 한글입력 상태(조합이 완료되지 않은 상태)에서 숫자, 특수 기호를 입력하면(쉬프트 누르고 입력하는 상태) 처음 문자는 정상적으로 입력되지만, 두 번째 입력 혹은 조합중이 아닌 경우에는 한글에서 영어 모드로 전환되면서 대문자가 입력됩니다.

**Comment by joonhwan** [comment]
#753 을 올렸는데, 여기 관련된 이슈가 이미 있었군요. 아아.
